# Generated by Django 5.2 on 2025-04-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='Assets/About-Images')),
                ('section_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('img1', models.ImageField(upload_to='Assets/About-Images')),
                ('img2', models.ImageField(upload_to='Assets/About-Images')),
            ],
        ),
        migrations.CreateModel(
            name='About_Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=50)),
                ('icon', models.CharField(help_text='should be in form of a string', max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Destinatiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=20)),
                ('location_img', models.ImageField(upload_to='Assets/Destination_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=255)),
                ('header_img', models.ImageField(upload_to='Assets/header-Images')),
                ('theme', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('period', models.CharField(max_length=20)),
                ('no_of_people', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('package_img', models.ImageField(upload_to='Assets/Packages_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='should be in form of a string', max_length=500)),
                ('sub_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
