# Generated by Django 5.2 on 2025-04-11 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinatiom',
            new_name='Destination',
        ),
    ]
