# Generated by Django 5.2 on 2025-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_destinatiom_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='section_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='section_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packages',
            name='section_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='section_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
