# Generated by Django 5.2 on 2025-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_about_section_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_img', models.ImageField(upload_to='Assets/header-Images')),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='header',
            name='header_img',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='section_title',
        ),
        migrations.RemoveField(
            model_name='service',
            name='section_title',
        ),
    ]
