# Generated by Django 5.2 on 2025-04-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_headerimages_remove_destination_section_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_Subsection',
            new_name='Feature',
        ),
    ]
